on: [push]

jobs:
  publish:
    name: Публикация релиза
    runs-on: ubuntu-latest
    
    steps:
      - name: Качаем репозиторий
        uses: actions/checkout@v2
      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0
      - name: Установка зависимостей и компиляция
        run: |
          npm install
          npm run build
      - name: Проверка папки
        run: ls -l
    
