name: Автоматическая публикация релизов

on:
  release:
    types: [published]

jobs:
  publish:
    name: Публикация релиза
    runs-on: ubuntu-latest

    steps:
      - name: Качаем репозиторий
        uses: actions/checkout@v2.3.4
      - name: Установка Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.13.0
      - name: Установка зависимостей и компиляция
        run: |
          npm install
          npm run build
      - name: Публикация релиза
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
